app:
    resource: '@AppBundle/Controller/'
    type: annotation

recambios:
    path:     /
    defaults: { _controller: "AppBundle:Default:index" }
    
recambios_productos:
    path:     /recambios-productos
    defaults: { _controller: "AppBundle:Default:recambios" }
    
recambios_alquiler:
    path:     /recambios-alquiler
    defaults: { _controller: "AppBundle:Default:alquiler" }    

informacion_recambios:
    path: /informacion
    defaults: { _controller: "AppBundle:Default:informacionrecambios" }
    
contacto_recambios:
    path: /contacto
    defaults: { _controller: "AppBundle:Default:contactorecambios" }    
    
    
registro_usuario:
    path:    /registro
    defaults: { _controller: "AppBundle:Registro:registroUsuario" }
    

login_usuario:
    path:    /login
    defaults: { _controller: "AppBundle:Login:log" }
    
logout:
    path: /logout
    defaults: