app:
    resource: '@AppBundle/Controller/'
    type: annotation

recambios:
    path:     /
    defaults: { _controller: "AppBundle:Default:index" }
    
recambios_productos:
    path:     /productos
    defaults: { _controller: "AppBundle:Default:recambios" }
    
recambios_alquiler:
    path:     /herramientas
    defaults: { _controller: "AppBundle:Default:alquiler" }    

informacion_recambios:
    path: /informacion
    defaults: { _controller: "AppBundle:Default:informacionrecambios" }
    
contacto_recambios:
    path: /contacto
    defaults: { _controller: "AppBundle:Default:contactorecambios" }    
    
    
registro_usuario:
    path:    /registro
    defaults: { _controller: "AppBundle:Registro:registroUsuario" }
    
    
administracion:
    path:   /admin
    defaults: { _controller: "AppBundle:Default:usuario"}
    

login_usuario:
    path:    /login
    defaults: { _controller: "AppBundle:Login:log" }
    
logout:
    path: /logout
    defaults: