alquiler_index:
    path:     /
    defaults: { _controller: "AppBundle:Alquiler:index" }
    methods:  GET

alquiler_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Alquiler:show" }
    methods:  GET

alquiler_new:
    path:     /new
    defaults: { _controller: "AppBundle:Alquiler:new" }
    methods:  [GET, POST]

alquiler_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Alquiler:edit" }
    methods:  [GET, POST]

alquiler_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Alquiler:delete" }
    methods:  DELETE
