comprar_index:
    path:     /
    defaults: { _controller: "AppBundle:Comprar:index" }
    methods:  GET

comprar_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Comprar:show" }
    methods:  GET

comprar_new:
    path:     /new
    defaults: { _controller: "AppBundle:Comprar:new" }
    methods:  [GET, POST]

comprar_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Comprar:edit" }
    methods:  [GET, POST]

comprar_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Comprar:delete" }
    methods:  DELETE
