inventario_index:
    path:     /
    defaults: { _controller: "AppBundle:Inventario:index" }
    methods:  GET

inventario_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Inventario:show" }
    methods:  GET

inventario_new:
    path:     /new
    defaults: { _controller: "AppBundle:Inventario:new" }
    methods:  [GET, POST]

inventario_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Inventario:edit" }
    methods:  [GET, POST]

inventario_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Inventario:delete" }
    methods:  DELETE
