AppBundle\Entity\Alquiler:
    type: entity
    table: alquiler
    indexes:
        fk_id_recambios:
            columns:
                - id_herramientas
        id_usuario:
            columns:
                - id_usuario
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        estado:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: ALQUILADO
        fechaAlquiler:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: fecha_alquiler
        megusta:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        comentarios:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
    manyToOne:
        idHerramientas:
            targetEntity: Herramientas
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_herramientas:
                    referencedColumnName: id
            orphanRemoval: false
        idUsuario:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_usuario:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
