AppBundle\Entity\Alquiler:
    type: entity
    table: alquiler
    indexes:
        fk_id_recambios:
            columns:
                - id_herramientas
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        estado:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    manyToOne:
        idHerramientas:
            targetEntity: Herramientas
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_herramientas:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
