AppBundle\Entity\Comprar:
    type: entity
    table: comprar
    indexes:
        fkk_id_recambios:
            columns:
                - id_recambios
        id_usuario:
            columns:
                - id_usuario
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        estado:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: COMPRADO
        fechaVenta:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: fecha_venta
        megusta:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        comentarios:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
    manyToOne:
        idRecambios:
            targetEntity: Recambios
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_recambios:
                    referencedColumnName: id
            orphanRemoval: false
        idUsuario:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_usuario:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
