AppBundle\Entity\Recambios:
    type: entity
    table: recambios
    uniqueConstraints:
        fecha_venta:
            columns:
                - fecha_creacion
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        contenido:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        marca:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        fechaCreacion:
            type: datetime
            nullable: false
            column: fecha_creacion
        img:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        precio:
            type: decimal
            nullable: false
            precision: 11
            scale: 2
    lifecycleCallbacks: {  }
